[feature] Readme and Plugin Information - feedback please
UniRegensburg/unsere-app-fur-die-universitat-regensburg-code-companion pull request #131
Opened 2021-04-11 08:30 UTC by goetzmat

2021-04-11 13:24 UTC, RealWhimsy requested changes
Needs a lot more information.

Add sections for every main-fragment (home, tasks, error messages, profile) and explain how to use them, what they do, and when they update. These explanations should be understandable by someone who has not seen anything about our app yet, so try to be as clear as possible, even if you think something is obvious.

Provide explanations for how external files, such as tasks.json, are used in our app (due date used for notifications 7, 3 and 1 day in advance, tasks are displayed in the tasks fragment, ...) , and how the user can interact with it. As it is right now, the structure of the tasks.json is shown nicely, but not explained what the fields are used for.

Also make sure that every main-fragment is explained **in detail**. For example:
Explain that the error-messages fragment updates in real-time and shows errors of the file the user currently has open in their IDE. The user can also tap on the errors to get additional information. From that screen, the user can also launch a google query for that error, either on their phone or the connected PC. Include a screenshot of an "error detail view".
The same goes for other categories, explain what the statistics mean, that the statistics displayed are either for the current project (if user is connected) or for all projects combined (if user is not connected).

**Plugin:**
As of right now, the plugin is barely explained in the readme.
Definitely should add the following:
- How to install it
- How to use it (include **screenshot** of tool window!)
- Explain how the user can see whether they are connected or not
- How the plugin behaves upon disconnecting (e.g. user closed the phone app)

Again, a lot of this information seems obvious and self-explanatory for us, but this should be a _very detailed_ explanation for people who have never ever seen our app and plugin.

If you need any help or more information let me know, I don't have any pressing issues to work on right now.

2021-04-11 13:24 UTC, RealWhimsy commented on README.md
> +![](Screenshot.png)
Create sections for every fragment. Add a screenshot of the fragment there, and explain in detail what the fragment does exactly

2021-04-11 13:24 UTC, RealWhimsy commented on README.md
> +A template project can be found -here-.
fix link to template project folder

2021-04-11 13:24 UTC, RealWhimsy commented on README.md
> +The "task.json" file is located inside the root of the project folder, and holds the project name, tasks and project due date.
Put this as a sub-sub-section of the **Task Fragment** overview. Make clear what the fields of the tasks.json do ("tasks" array is what is displayed in the app etc.) and explain what happens when no tasks.json is present

2021-04-11 13:24 UTC, RealWhimsy commented on README.md
> +Code Companion is developed by Fabian (@PLACEBOBRO) Lukas (@RealWhimsy) Mathias (@goetzmat) and Maximilian (@MaximilianSeewald) during the "Advanced Software Engineering" Course of Uni Regensburg.
add commas after each person

2021-04-11 13:24 UTC, RealWhimsy commented on README.md
> +
missing plugin explanations + screenshots

2021-04-11 13:29 UTC, RealWhimsy commented
Maybe also add a short **Requirements** section to the top:
IntelliJ IDEA Community version x.xx (tbd)
Smartphone running Android 6.0 (Marshmallow) or higher

2021-04-12 10:35 UTC, RealWhimsy approved these changes
[DOCUMENTATION]
Feature: read-me
Created by: @goetzmat 
Review by: @RealWhimsy 
Working: Yes
Documentation: Top
Clean code:  Yes
Notes: Looks solid, good job on implementing the previous feedback

2021-04-12 10:36 UTC, MaximilianSeewald approved these changes
[DOCUMENTATION]
Feature: read-me
Created by: @goetzmat
Review by: @MaximilianSeewald 
Working: Yes
Documentation: Top
Clean code: Yes
Notes:

2021-04-12 10:37 UTC, merged